#Requires -Version 7.0
# New-WeeklyReport.ps1 — Aggregate weekly learning report
# Usage:  noeau report weekly

param([string]$WeekOf = "")

$here = $PSScriptRoot
Import-Module (Join-Path $here "modules\NoEau.psm1") -Force

$weekStart = if ($WeekOf) { $WeekOf } else { Get-WeekStart }
$weekEnd   = ([datetime]::ParseExact($weekStart, "yyyy-MM-dd", $null)).AddDays(6).ToString("yyyy-MM-dd")
$today     = Get-TodayStr
if ($weekEnd -gt $today) { $weekEnd = $today }

$reportsDir = Get-NoEauPath "reports\weekly"
$yearWeek   = "$($weekStart.Substring(0,4))-W$((Get-Culture).Calendar.GetWeekOfYear([datetime]::ParseExact($weekStart,"yyyy-MM-dd",$null),[System.Globalization.CalendarWeekRule]::FirstDay,[DayOfWeek]::Monday).ToString('D2'))"
$outputFile = Join-Path $reportsDir "$yearWeek.md"

$config  = Get-NoEauConfig
$tracker = Get-LearningTracker

Write-Host "  Generating weekly report: $weekStart → $weekEnd ..." -ForegroundColor Cyan

$sessions  = @($tracker.sessions | Where-Object { $_.date -ge $weekStart -and $_.date -le $weekEnd })
$captures  = @(Get-CapturesByDateRange -From $weekStart -To $weekEnd)
$totalMin  = if ($sessions.Count) { [int]($sessions | Measure-Object -Property duration_minutes -Sum).Sum } else { 0 }
$goalMin   = [int]$config.goals.daily_learning_minutes
$weekGoal  = $goalMin * 7

# Per-topic aggregation
$topicAgg = @{}
foreach ($s in $sessions) {
    $t = $s.topic
    if (-not $topicAgg.ContainsKey($t)) { $topicAgg[$t] = @{ minutes = 0; sessions = 0; notes = 0 } }
    $topicAgg[$t].minutes  += [int]$s.duration_minutes
    $topicAgg[$t].sessions += 1
}
foreach ($c in $captures) {
    $t = Split-Path (Split-Path $c.FullName) -Leaf
    if (-not $topicAgg.ContainsKey($t)) { $topicAgg[$t] = @{ minutes = 0; sessions = 0; notes = 0 } }
    $topicAgg[$t].notes += 1
}

# Per-day breakdown
$dayBreakdown = @{}
for ($i = 0; $i -le 6; $i++) {
    $d = ([datetime]::ParseExact($weekStart,"yyyy-MM-dd",$null)).AddDays($i).ToString("yyyy-MM-dd")
    if ($d -gt $today) { break }
    $daySessions = @($sessions | Where-Object { $_.date -eq $d })
    $dayMin = if ($daySessions.Count) { [int]($daySessions | Measure-Object -Property duration_minutes -Sum).Sum } else { 0 }
    $dayBreakdown[$d] = $dayMin
}

$pct   = if ($weekGoal -gt 0) { [Math]::Min(100, [int](($totalMin / $weekGoal) * 100)) } else { 0 }
$ws    = [datetime]::ParseExact($weekStart,"yyyy-MM-dd",$null)
$we    = [datetime]::ParseExact($weekEnd,"yyyy-MM-dd",$null)

$md = @"
# Weekly Learning Report — $yearWeek

> *$($ws.ToString("MMMM d")) – $($we.ToString("MMMM d, yyyy"))*

---

## Summary

| Field | Value |
|-------|-------|
| Total learning time | $totalMin min |
| Weekly goal ($($weekGoal) min) | $pct% |
| Notes captured | $($captures.Count) |
| Active topics | $($topicAgg.Keys.Count) |
| Learning days | $($dayBreakdown.Values | Where-Object { $_ -gt 0 } | Measure-Object | Select-Object -ExpandProperty Count) / 7 |

---

## Daily Breakdown

| Date | Day | Minutes | Goal ($goalMin) |
|------|-----|---------|-----------------|
"@

foreach ($d in ($dayBreakdown.Keys | Sort-Object)) {
    $dayObj = [datetime]::ParseExact($d,"yyyy-MM-dd",$null)
    $mins   = $dayBreakdown[$d]
    $pctDay = if ($goalMin -gt 0) { [Math]::Min(100, [int](($mins / $goalMin) * 100)) } else { 0 }
    $status = if ($mins -ge $goalMin) { "✓" } elseif ($mins -gt 0) { "$pctDay%" } else { "—" }
    $md += "| $d | $($dayObj.ToString('ddd')) | $mins | $status |`n"
}

$md += "`n---`n`n## Topic Breakdown`n`n"
$md += "| Topic | Minutes | Sessions | Notes |`n"
$md += "|-------|---------|----------|-------|`n"
foreach ($entry in ($topicAgg.GetEnumerator() | Sort-Object { $_.Value.minutes } -Descending)) {
    $md += "| $($entry.Key) | $($entry.Value.minutes) | $($entry.Value.sessions) | $($entry.Value.notes) |`n"
}

$md += "`n---`n`n## Notes Captured This Week`n`n"
foreach ($c in ($captures | Sort-Object LastWriteTime)) {
    $tDir  = Split-Path (Split-Path $c.FullName) -Leaf
    $title = $c.BaseName -replace "^\d{4}-\d{2}-\d{2}-","" -replace "-"," "
    $md += "- **[$tDir]** $title  *($(Split-Path $c.FullName))*`n"
}

$md += "`n---`n"
$md += "*Generated by Noʻeau Knowledge System v1.0 — $(Get-Date -Format 'yyyy-MM-dd HH:mm')*`n"

Set-Content $outputFile -Value $md -Encoding UTF8

Write-Host "  ✓ Saved: $outputFile" -ForegroundColor Green
Write-Host ""
$open = Read-Host "  Open report? (Y/n)"
if ($open.Trim().ToLower() -ne 'n') { Start-Process $outputFile }
