#Requires -Version 7.0
# New-DailyReport.ps1 — Generate today's (or a given date's) markdown report
# Usage:  noeau report daily
#         noeau report daily 2025-06-08

param([string]$Date = "")

$here = $PSScriptRoot
Import-Module (Join-Path $here "modules\NoEau.psm1") -Force

if (-not $Date) { $Date = Get-TodayStr }

$reportsDir = Get-NoEauPath "reports\daily"
$outputFile = Join-Path $reportsDir "$Date.md"
$config     = Get-NoEauConfig
$tracker    = Get-LearningTracker

Write-Host "  Generating daily report: $Date ..." -ForegroundColor Cyan

$sessions   = @($tracker.sessions | Where-Object { $_.date -eq $Date })
$captures   = @(Get-CapturesByDateRange -From $Date -To $Date)
$streak     = Get-StreakInfo

$totalMin   = if ($sessions.Count) { [int]($sessions | Measure-Object -Property duration_minutes -Sum).Sum } else { 0 }
$topicList  = ($sessions | ForEach-Object { $_.topic } | Sort-Object -Unique) -join ", "
if (-not $topicList) { $topicList = "—" }

$dateObj    = [datetime]::ParseExact($Date, "yyyy-MM-dd", $null)
$dayDisplay = $dateObj.ToString("dddd, MMMM d, yyyy")
$goalMin    = [int]$config.goals.daily_learning_minutes
$pct        = if ($goalMin -gt 0) { [Math]::Min(100, [int](($totalMin / $goalMin) * 100)) } else { 0 }

# ── Markdown content ───────────────────────────────────────────────────────────

$md = @"
# Daily Learning Report — $Date

> *$dayDisplay*

---

## Summary

| Field | Value |
|-------|-------|
| Topics covered | $topicList |
| Total learning time | $totalMin min |
| Goal ($goalMin min) | $pct% |
| Notes captured | $($captures.Count) |
| Streak | $($streak.current) days |

---

"@

# Knowledge captures
if ($captures.Count -gt 0) {
    $md += "## Knowledge Captured`n`n"
    foreach ($f in ($captures | Sort-Object LastWriteTime)) {
        $topicDir = Split-Path (Split-Path $f.FullName) -Leaf
        $title    = $f.BaseName -replace "^\d{4}-\d{2}-\d{2}-","" -replace "-"," "
        $raw      = Get-Content $f.FullName -Raw -Encoding UTF8

        # Pull a short preview from body (skip frontmatter and headings)
        $body  = ($raw -split "`n" | Where-Object { $_ -and $_ -notmatch '^(---|#|tags:|title:|date:|minutes:|topic:|---|\*Captured)' }) -join " "
        $preview = if ($body.Length -gt 220) { $body.Substring(0, 220) + "…" } else { $body }

        $md += "### [$topicDir] $title`n`n"
        $md += "*``$($f.FullName)``*`n`n"
        if ($preview.Trim()) { $md += "> $($preview.Trim())`n`n" }
        $md += "---`n`n"
    }
}

# Learning sessions table
if ($sessions.Count -gt 0) {
    $md += "## Learning Sessions`n`n"
    $md += "| Topic | Minutes | Notes | Tags |`n"
    $md += "|-------|---------|-------|------|`n"
    foreach ($s in $sessions) {
        $tagStr = if ($s.tags -and @($s.tags).Count -gt 0) { @($s.tags) -join ", " } else { "" }
        $md += "| $($s.topic) | $($s.duration_minutes) | $($s.notes) | $tagStr |`n"
    }
    $md += "`n"
}

# Streak
$flames = "🔥" * [Math]::Min($streak.current, 10)
$md += "## Streak`n`n"
$md += "Current: **$($streak.current) days** $flames`n`n"
$md += "Longest: **$($streak.longest) days**`n`n"

# Footer
$md += "---`n"
$md += "*Generated by Noʻeau Knowledge System v1.0 — $(Get-Date -Format 'yyyy-MM-dd HH:mm')*`n"

Set-Content $outputFile -Value $md -Encoding UTF8

Write-Host "  ✓ Saved: $outputFile" -ForegroundColor Green
Write-Host ""

$open = Read-Host "  Open report? (Y/n)"
if ($open.Trim().ToLower() -ne 'n') { Start-Process $outputFile }
