#Requires -Version 7.0
# New-MonthlyReport.ps1 — Monthly progress report
# Usage:  noeau report monthly

param([string]$Month = "")

$here = $PSScriptRoot
Import-Module (Join-Path $here "modules\NoEau.psm1") -Force

if (-not $Month) { $Month = Get-MonthStr }   # e.g. "2025-06"

$monthStart = "${Month}-01"
$monthObj   = [datetime]::ParseExact($monthStart, "yyyy-MM-dd", $null)
$monthEnd   = $monthObj.AddMonths(1).AddDays(-1).ToString("yyyy-MM-dd")
$today      = Get-TodayStr
if ($monthEnd -gt $today) { $monthEnd = $today }

$reportsDir = Get-NoEauPath "reports\monthly"
$outputFile = Join-Path $reportsDir "$Month.md"
$config     = Get-NoEauConfig
$tracker    = Get-LearningTracker

Write-Host "  Generating monthly report: $Month ..." -ForegroundColor Cyan

$sessions  = @($tracker.sessions | Where-Object { $_.date -ge $monthStart -and $_.date -le $monthEnd })
$captures  = @(Get-CapturesByDateRange -From $monthStart -To $monthEnd)
$totalMin  = if ($sessions.Count) { [int]($sessions | Measure-Object -Property duration_minutes -Sum).Sum } else { 0 }

# Topic aggregation
$topicAgg = @{}
foreach ($s in $sessions) {
    $t = $s.topic
    if (-not $topicAgg.ContainsKey($t)) { $topicAgg[$t] = @{ minutes = 0; sessions = 0; notes = 0 } }
    $topicAgg[$t].minutes  += [int]$s.duration_minutes
    $topicAgg[$t].sessions += 1
}
foreach ($c in $captures) {
    $t = Split-Path (Split-Path $c.FullName) -Leaf
    if (-not $topicAgg.ContainsKey($t)) { $topicAgg[$t] = @{ minutes = 0; sessions = 0; notes = 0 } }
    $topicAgg[$t].notes += 1
}

# Week-by-week breakdown
$weekRows = @()
$ptr      = $monthObj
while ($ptr.ToString("yyyy-MM-dd") -le $monthEnd) {
    $wEnd = [Math]::Min(($ptr.AddDays(6) - $monthObj).TotalDays, ($monthObj.AddMonths(1).AddDays(-1) - $monthObj).TotalDays)
    $wEnd = $ptr.AddDays(6)
    if ($wEnd.ToString("yyyy-MM") -ne $Month) { $wEnd = $monthObj.AddMonths(1).AddDays(-1) }
    if ($wEnd.ToString("yyyy-MM-dd") -gt $today) { $wEnd = [datetime]::ParseExact($today,"yyyy-MM-dd",$null) }

    $ws = $ptr.ToString("yyyy-MM-dd")
    $we = $wEnd.ToString("yyyy-MM-dd")

    $wSessions = @($sessions | Where-Object { $_.date -ge $ws -and $_.date -le $we })
    $wMin = if ($wSessions.Count) { [int]($wSessions | Measure-Object -Property duration_minutes -Sum).Sum } else { 0 }
    $wNotes = @($captures | Where-Object { $_.LastWriteTime.ToString("yyyy-MM-dd") -ge $ws -and $_.LastWriteTime.ToString("yyyy-MM-dd") -le $we }).Count

    $weekRows += "| $($ptr.ToString('MMM d')) – $($wEnd.ToString('MMM d')) | $wMin | $wNotes |"
    $ptr = $ptr.AddDays(7)
    if ($ptr.ToString("yyyy-MM") -ne $Month) { break }
}

$activeDays = ($sessions | ForEach-Object { $_.date } | Sort-Object -Unique | Measure-Object).Count
$daysInRange= ([datetime]::ParseExact($monthEnd,"yyyy-MM-dd",$null) - $monthObj).Days + 1
$avgPerDay  = if ($activeDays -gt 0) { [Math]::Round($totalMin / $activeDays) } else { 0 }
$pdfCount   = @(Get-ChildItem (Get-NoEauPath "research\PDFs") -Filter "*.pdf" -ErrorAction SilentlyContinue).Count

$md = @"
# Monthly Progress Report — $($monthObj.ToString("MMMM yyyy"))

---

## Overview

| Metric | Value |
|--------|-------|
| Total learning time | $totalMin min |
| Active learning days | $activeDays / $daysInRange |
| Avg per active day | $avgPerDay min |
| Notes captured | $($captures.Count) |
| PDFs in library | $pdfCount |
| Topics active | $($topicAgg.Keys.Count) |

---

## Weekly Breakdown

| Week | Minutes | Notes |
|------|---------|-------|
$($weekRows -join "`n")

---

## Topic Progress

| Topic | Minutes | Sessions | Notes | Focus % |
|-------|---------|----------|-------|---------|
"@

foreach ($entry in ($topicAgg.GetEnumerator() | Sort-Object { $_.Value.minutes } -Descending)) {
    $focusPct = if ($totalMin -gt 0) { [Math]::Round($entry.Value.minutes / $totalMin * 100) } else { 0 }
    $md += "| $($entry.Key) | $($entry.Value.minutes) | $($entry.Value.sessions) | $($entry.Value.notes) | $focusPct% |`n"
}

# Reflection prompts (Obsidian-friendly)
$md += @"

---

## Monthly Reflection

> *Fill these in when reviewing the month.*

**What did I learn that surprised me?**


**Which topic needs more focus next month?**


**What habit served me best this month?**


**One thing to apply or practice next month:**


---
*Generated by Noʻeau Knowledge System v1.0 — $(Get-Date -Format 'yyyy-MM-dd HH:mm')*
"@

Set-Content $outputFile -Value $md -Encoding UTF8

Write-Host "  ✓ Saved: $outputFile" -ForegroundColor Green
Write-Host ""
$open = Read-Host "  Open report? (Y/n)"
if ($open.Trim().ToLower() -ne 'n') { Start-Process $outputFile }
