#!/usr/bin/env python3
"""
Noʻeau PDF Processor
Extracts text from a PDF and writes a markdown summary to the summaries folder.

Usage:
    python pdf_processor.py <pdf_path> <output_dir>

Output (to stdout, JSON):
    {"status": "ok", "topic": "...", "summary_path": "...", "pages": N, "words": N}
"""

import sys
import json
import re
from pathlib import Path
from datetime import datetime

# ── PDF backend ──────────────────────────────────────────────────────────────

try:
    import pdfplumber
    _PDF_BACKEND = "pdfplumber"
except ImportError:
    print(json.dumps({"status": "error", "message":
          "pdfplumber not installed. Run: pip install pdfplumber"}))
    sys.exit(1)

# ── Text extraction ──────────────────────────────────────────────────────────

def extract_text(pdf_path: Path) -> tuple[str, int]:
    """Return (full_text, page_count)."""
    pages_text = []
    with pdfplumber.open(pdf_path) as pdf:
        page_count = len(pdf.pages)
        for page in pdf.pages:
            t = page.extract_text()
            if t:
                pages_text.append(t)
    return "\n\n".join(pages_text), page_count

# ── Topic detection ──────────────────────────────────────────────────────────

_TOPIC_KEYWORDS: dict[str, list[str]] = {
    "python":             ["python","django","flask","numpy","pandas","pip","venv","async","def ","class "],
    "linux":              ["linux","bash","chmod","grep","sudo","systemctl","apt","debian","ubuntu","kali"],
    "networking":         ["tcp","ip address","dns","dhcp","http","subnet","router","vlan","osi model","packet"],
    "cybersecurity":      ["exploit","vulnerability","cve","pentest","payload","malware","firewall","zero-day"],
    "osint":              ["osint","reconnaissance","shodan","maltego","footprinting","intelligence gathering"],
    "lds-studies":        ["latter-day saints","book of mormon","scriptures","covenant","priesthood","gospel","jesus christ"],
    "personal-development": ["habit","productivity","mindset","discipline","growth","motivation","journaling"],
}

def detect_topic(text: str) -> str:
    lower = text.lower()
    scores = {t: sum(1 for kw in kws if kw in lower) for t, kws in _TOPIC_KEYWORDS.items()}
    best = max(scores, key=scores.get)
    return best if scores[best] > 0 else "research"

# ── Key point extraction ─────────────────────────────────────────────────────

def extract_key_points(text: str, max_points: int = 8) -> list[str]:
    # Split on sentence boundaries
    sentences = re.split(r'(?<=[.!?])\s+', text)
    sentences = [s.strip() for s in sentences if 50 < len(s.strip()) < 300]

    importance_words = [
        "important", "note that", "key", "critical", "define", "means",
        "therefore", "conclusion", "result", "first", "second", "third",
        "remember", "essential", "must", "always", "never"
    ]

    def score(s: str) -> int:
        lower = s.lower()
        return sum(2 for w in importance_words if w in lower) + (1 if re.search(r'\b\d+\b', s) else 0)

    ranked = sorted(sentences, key=score, reverse=True)
    return ranked[:max_points]

# ── Summary writer ────────────────────────────────────────────────────────────

def create_summary(pdf_path: Path, output_dir: Path) -> dict:
    print(f"[noeau] Processing: {pdf_path.name}", file=sys.stderr)

    text, page_count = extract_text(pdf_path)
    if not text.strip():
        text = "[This PDF appears to be image-based — text extraction not available. " \
               "Consider using OCR software.]"

    topic      = detect_topic(text)
    key_points = extract_key_points(text)
    word_count = len(text.split())
    today      = datetime.now().strftime("%Y-%m-%d")
    stem       = pdf_path.stem

    points_md = "\n".join(f"- {p}" for p in key_points) if key_points else "- (No key points extracted)"

    preview = text[:2500] + ("…" if len(text) > 2500 else "")
    preview_escaped = preview.replace("```", "~~~")

    summary = f"""---
title: "{stem}"
date: {today}
topic: {topic}
source: "{pdf_path.name}"
pages: {page_count}
words: {word_count}
type: pdf-summary
---

# {stem}

> **Source:** `{pdf_path.name}`
> **Pages:** {page_count}  ·  **Words:** ~{word_count:,}
> **Topic:** {topic}
> **Processed:** {datetime.now().strftime("%Y-%m-%d %H:%M")}

---

## Key Points

{points_md}

---

## Text Preview

```
{preview_escaped}
```

---
*Summary generated by Noʻeau Knowledge System*
"""

    output_dir.mkdir(parents=True, exist_ok=True)
    out_path = output_dir / f"{today}-{stem}-summary.md"
    out_path.write_text(summary, encoding="utf-8")

    return {
        "status":       "ok",
        "topic":        topic,
        "summary_path": str(out_path),
        "pages":        page_count,
        "words":        word_count,
    }

# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: pdf_processor.py <pdf_path> <output_dir>", file=sys.stderr)
        sys.exit(1)

    pdf_path   = Path(sys.argv[1])
    output_dir = Path(sys.argv[2])

    if not pdf_path.exists():
        print(json.dumps({"status": "error", "message": f"File not found: {pdf_path}"}))
        sys.exit(1)

    result = create_summary(pdf_path, output_dir)
    print(json.dumps(result))
